version: '3.8'

services:
  app:
    image: m1m1kq/oxcs
    ports:
      - "${APP_PORT}:6000"
    volumes:
       - "~/apps-data/${COMPANY}/files-data/:/app/assets/uploads/"
    depends_on:
      db:
        condition: service_healthy
      app-converter:
        condition: service_started
    environment:
      PORT: 6000
      APP_ADDRESS: "${APP_URL}:${APP_PORT}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: "${DB}"
      DB_NAME: "${DB}"
      DB_SSLMODE: disable
  app-converter:
    restart: always
    image: m1m1kq/oxcs-converter
    ports:
      - "${CONVERTER_PORT}:5000"
    environment:
      APP_ADDR: http://app:6000
  db:
    restart: always
    image: postgres:latest
    volumes:
      - "~/apps-data/${COMPANY}/tables-data/:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "${DB}"
      POSTGRES_USER: "${DB}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_OUT_PORT}:5432"